Implementing Overlay
Dummyrunner/LandingGame pull request #10
Opened 2024-09-29 09:20 UTC by beneblubb

# Implemented Overlays for different purposes

## New Class: Overlay
- Child of LandingGameObject.
- Takes (in addition to image and position) a list of objects, whose attributes shall be displayed.

## New Class: GameStatistics
- Class for storing information about the running game (time, level, ...)

## Changes in Main
- Implementation of GameStatistics and Overlays
-- Overlay for GameStatistics
-- Overlay for displaying Information about the current game Objects for debugging
-- Overlays are added to the obj_list after it is passed to the debug display, so the overlays are not shown in the debugging overlay

2024-09-29 16:00 UTC, Dummyrunner requested changes

2024-09-29 18:53 UTC, beneblubb commented on src/game_statistics.py
> +        self.score = 0
Random stuff deleted

2024-09-29 18:56 UTC, beneblubb commented on src/game_statistics.py
> +        self.score = 0
But Test Class not yet updated (reason: sleep)

2024-10-01 15:11 UTC, Dummyrunner requested changes
Added some more thoughts we could address

2024-10-01 20:11 UTC, beneblubb commented on src/game_statistics.py
> +class GameStatistics:
Still working on other fixes, name will be changed later

2024-10-01 20:12 UTC, beneblubb commented on src/game_statistics.py
> +        self.time_in_seconds = 0
Working on Overlay class so it can handle displaying floats as integers

2024-10-01 20:12 UTC, beneblubb commented on src/game_statistics.py
> +    def get_time_in_seconds(self) -> int:
Will be deleted

2024-10-01 20:13 UTC, beneblubb commented on src/overlay.py
> +    def __init__(self, image, position=(0, 0), objects_to_display="None"):
Sure, was a typing error

2024-10-01 20:13 UTC, beneblubb commented on src/overlay.py
> +        fontsize = 16
Already done

2024-10-01 20:15 UTC, beneblubb commented on src/overlay.py
> +    def render_text(self, fontsize=16):
Completely worked over. Several times.

2024-10-01 20:15 UTC, beneblubb commented on src/overlay.py
> +            text_surface = self.font.render(line, True, (255, 255, 255))
Hupsi

2024-10-03 10:36 UTC, beneblubb commented
Take that!

2024-10-03 10:43 UTC, beneblubb commented on src/overlay.py
> +            text_surface = self.font.render(line, True, (255, 255, 255))
In this class, using rgb values ist better than making a new import, so there are fewer dependencys.

2024-10-03 10:46 UTC, beneblubb commented on main.py
> +def create_overlays():
Maybe this function could be moved into a different file to make main.py more readable / more fokused.

2024-10-03 14:56 UTC, Dummyrunner commented on src/overlay.py
> +            text_surface = self.font.render(line, True, (255, 255, 255))
No.

2024-10-03 15:06 UTC, beneblubb commented on src/overlay.py
> +            text_surface = self.font.render(line, True, (255, 255, 255))
Was worth a try

2024-10-03 17:24 UTC, Dummyrunner commented on src/overlay.py
> +            text_surface = self.font.render(line, True, (255, 255, 255))
No.

2024-10-04 08:05 UTC, Dummyrunner requested changes
Cool! I like the overlay concept a lot now, noted some smaller ideas for improvement. Also the tests are nice!

2024-10-04 08:05 UTC, Dummyrunner commented on src/overlay.py
> +                f"{attribute_display_name}: {float(obj.__dict__[attribute_name]):.2f}"
why not leave the choice `.2f` to be handed in with the attribute format?

2024-10-04 10:08 UTC, beneblubb commented on src/common_constants.py
> +@dataclass(frozen=True)
Re-wrote that entire class at least 3 times, thought that I resetted it to a state where the Colours were not defined.

2024-10-04 10:10 UTC, beneblubb commented on src/overlay.py
> +    Overlay class to display information on the screen.
Already wrote Docstrings after pushing, as well as some other small changes. Will be in the next pr.

2024-10-04 10:12 UTC, beneblubb commented on test/test_overlay.py
> +def test_render_text(overlay):
Thought about deleting the method, but leaving it this way makes visible, that this method of the class is not tested. And maybe you know a good way to test if sonething is shown on the screen?

2024-10-04 10:12 UTC, beneblubb commented on test/test_overlay.py
> +def test_add_line(overlay):
Thx

2024-10-04 10:13 UTC, beneblubb commented on src/overlay.py
> +        alpha: int = 128,
Good Idea

2024-10-04 10:16 UTC, beneblubb commented on src/overlay.py
> +import pygame
More customisation are already in a different branch, but those will be worked on when this pr is finally done

2024-10-04 16:17 UTC, Dummyrunner commented on src/overlay.py
> +                f"{attribute_display_name}: {float(obj.__dict__[attribute_name]):.2f}"
no, i mean including it to an existing one

2024-10-04 16:19 UTC, Dummyrunner commented on test/test_overlay.py
> +def test_render_text(overlay):
No, sadly I dont know yet. this is a topic for many of our components in general. cluttering the files with non-sense tests does not really bring benefit

2024-10-04 16:19 UTC, Dummyrunner commented on src/overlay.py
> +                f"{attribute_display_name}: {float(obj.__dict__[attribute_name]):.2f}"
we can leave it for now

2024-10-04 16:21 UTC, Dummyrunner commented on src/overlay.py
> +            raise ValueError("Line must be of type int, float, or str")
`TypeError` is also a predefined error type that could be more suitable here

2024-10-04 16:21 UTC, Dummyrunner commented on src/overlay.py
> +    Overlay class to display information on the screen.
teethgrinding "ok"

2024-10-04 16:21 UTC, Dummyrunner commented on src/common_constants.py
> +@dataclass(frozen=True)
ok. and now?

2024-10-04 18:15 UTC, beneblubb commented on src/common_constants.py
> +@dataclass(frozen=True)
Used old color_dict

2024-10-04 18:18 UTC, beneblubb commented on test/test_overlay.py
> +def test_render_text(overlay):
Useless tests deleted

2024-10-04 18:19 UTC, beneblubb commented on src/overlay.py
> +        alpha: int = 128,
Implemented Constants for full, half and no transparency

2024-10-04 18:41 UTC, Dummyrunner approved these changes

2024-10-04 18:43 UTC, merged