Overlay additional functionality
Dummyrunner/LandingGame pull request #21
Opened 2024-10-05 10:11 UTC by beneblubb

Overlay class should work as intended.
Remaining Problem: Not possible to toggle Visibility by pressing a button once. So it toggles the visibility 60 times a second until you release the key. Makes it kind of random.

2024-10-05 10:13 UTC, beneblubb commented on main.py
> +)
Is it better to merge it like this or wait until the underlying bug is fixed and adjust the code of this pr before merging?

2024-10-08 08:36 UTC, beneblubb commented
This draft will be finished after Issue #20 is resolved.

2024-10-08 20:20 UTC, Dummyrunner requested changes
* clarify naming of key press events
* clarify concept of key press when hold down is not required
* create unit tests that mock key input

2024-10-14 16:41 UTC, beneblubb commented
@Dummyrunner I fit this PR to the current state of main (with the possibility to trigger an event on pressing down a key)

2024-10-15 08:27 UTC, Dummyrunner approved these changes

2024-10-15 08:28 UTC, merged